"""Description of changes9

Revision ID: e171d063c382
Revises: d54fb3667879
Create Date: 2023-12-06 16:13:37.828075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e171d063c382'
down_revision = 'd54fb3667879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wishList')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishList', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
